```{r cef-level2-text}
cz=c("@@cz_index@@", "@@cz_type@@")

# define cz
ez <- as.numeric(cz[[1]])
cztype <- cz[[2]]

# define ranges and import data
## 1st sheet
sheet <- if_else(cztype == "terminal",
                 if_else(ez >1, paste0("5_TRM (", ez, ")"), "5_TRM"),
                 "1_ERT")
ceff_file <- if_else(country == "Spain" & ez == 2, ceff_file_canarias, ceff_file)

## range 1.4
range <- "C50:M71"
cef_txt_1_4  <- read_range(ceff_file, sheet, range) %>% rename(a = 1)
### find specific headings
my_index_su <- which(cef_txt_1_4$a %like% paste0(if_else(cztype == "terminal",
                                                         "Terminal",
                                                         "En route"), 
                                                 ' service units')) + 1

if(identical(my_index_su, numeric(0)) == TRUE) {my_index_su <- which(cef_txt_1_4$a %like% paste0("Terminal charging zone ", ez,' service units')) + 1} 

my_index_cost_by_ent <- which(cef_txt_1_4$a %like% paste0(if_else(cztype == "terminal",
                                                         "Terminal",
                                                         "En route"), 
                                                 ' costs by entity')) + 1

if(identical(my_index_cost_by_ent, numeric(0)) == TRUE) {my_index_cost_by_ent <- which(cef_txt_1_4$a %like% paste0("Terminal charging zone ", ez,' costs by entity')) + 1} 

my_index_cost_main <- which(cef_txt_1_4$a %like% paste0(if_else(cztype == "terminal",
                                                         "Terminal",
                                                         "En route"), 
                                                 " costs for the main ANSP")) + 1

if(identical(my_index_cost_main, numeric(0)) == TRUE) {my_index_cost_main <- which(cef_txt_1_4$a %like% paste0("Terminal charging zone ", ez,' costs for the main ANSP')) + 1} 

## 2nd sheet
sheet <- if_else(cztype == "terminal",
                 if_else(ez >1, paste0("6_TRM (", ez, ")"), "6_TRM"),
                 "2_ERT")
range <- "C11:M14"
cef_txt_1_5  <- read_range(ceff_file, sheet, range)

range <- "J16:M33"
cef_txt_1_6  <- read_range(ceff_file, sheet, range)

## range 1.9
range <- "C63:M70"
cef_txt_1_9  <- read_range(ceff_file, sheet, range)

## 3rd sheet
sheet <- if_else(cztype == "terminal",
                 if_else(ez >1, paste0("7_TRM_ATSP (", ez, ")"), "7_TRM_ATSP"),
                 "3_ATSP")

range <- "C11:M22"
cef_txt_1_10  <- read_range(ceff_file, sheet, range)

range <- "C66:M71"
cef_txt_1_13  <- read_range(ceff_file, sheet, range)
```

[4 Cost-efficiency]{class="fakeh1"}

## @@cz_type_proper@@ CZ - {{< var doc.@@cz_short@@@@cz_index@@ >}}

::: {#container-cef-duc style="clear: both"}

### KPI – DUC/AUC, costs and SUs

<!-- empty line to ensure next heading leaves enough space -->
<div style="height: 1px"></div>

:::: {#chart-cef-duc class="mychart"}
```{r chart-cef-duc, options = (cz=c("@@cz_index@@", "@@cz_type@@"))}
#| file: R/chart_level1_cef.R
#| out.width: "100%"
```
::::

:::: {#concl-cef-duc}
```{r concl-cef-duc}
# cef_conc <- read_mytable("PRB_findings.xlsx", "cost-efficiency", "Table_Findings_CEFF") %>% 
#   filter(Year_Report == params$year_report, State == params$country) %>% 
#   select(Conclusion) %>% toString() %>% paste0(., "@")
# 
# cef_conc1 <- cef_conc %>% str_replace_all(c('", ' = '\n\n', '\"' = '', '\n\n\n' = '\n\n')) %>% str_replace(fixed('c('), '') %>%  str_replace(fixed(')@'), '\n') 
```

`r cef_txt_1_4[2,1]`
::::
:::

::: {#container-cef-su style="clear: both"}

<!-- empty line to ensure next heading leaves enough space -->
<div style="height: 1px"></div>

:::: {#chart-cef-su class="mychart"}
```{r chart-cef-su, options = (cz=c("@@cz_index@@", "@@cz_type@@"))}
#| file: R/chart_level2_cef_su.R
#| out.width: "100%"
```
::::

:::: {#concl-cef-su}

`r cef_txt_1_4[my_index_su,1]`

::::
:::

::: {#container-cef-cost style="clear: both"}

<!-- empty line to ensure next heading leaves enough space -->
<div style="height: 1px"></div>

:::: {#chart-cef-cost class="mychart"}
```{r chart-cef-cost, options = (cz=c("@@cz_index@@", "@@cz_type@@"))}
#| file: R/chart_level2_cef_cost.R
#| out.width: "100%"
```

```{r table-cef-cost, options = (cz=c("@@cz_index@@", "@@cz_type@@"))}
#| file: R/table_level2_cef_cost.R
#| out.width: "100%"
```

```{r table-cef-cost-infl, options = (cz=c("@@cz_index@@", "@@cz_type@@"))}
#| file: R/table_level2_cef_cost_infl.R
#| out.width: "100%"
```

::::

:::: {#concl-cef-cost}


::::
:::

::: {#container-cef-cost-entity style="clear: both"}

<!-- empty line to ensure next heading leaves enough space -->
<div style="height: 1px"></div>

:::: {#chart-cef-cost-entity class="mychart"}
```{r chart-cef-cost-entity, options = (cz=c("@@cz_index@@", "@@cz_type@@"))}
#| file: R/chart_level2_cef_cost_entity.R
#| out.width: "100%"
```
::::

:::: {#concl-cef-cost-entity}

`r cef_txt_1_4[my_index_cost_by_ent,1]`

::::
:::

::: {#container-cef-cost-main style="clear: both"}

<!-- empty line to ensure next heading leaves enough space -->
<div style="height: 1px"></div>

:::: {#chart-cef-cost-main class="mychart"}
```{r chart-cef-cost-main, options = (cz=c("@@cz_index@@", "@@cz_type@@"))}
#| file: R/chart_level2_cef_cost_main.R
#| out.width: "100%"
```
::::

:::: {#concl-cef-cost-main}

`r cef_txt_1_4[my_index_cost_main,1]`

::::
:::

::: {#container-cef-aucu style="clear: both"}

<!-- empty line to ensure next heading leaves enough space -->
<div style="height: 1px"></div>

:::: {#chart-cef-aucu class="mychart"}
```{r chart-cef-aucu, options = (cz=c("1", "enroute"))}
#| file: R/chart_level2_cef_aucu.R
#| out.width: "100%"
```

```{r table-cef-aucu, options = (cz=c("1", "enroute"))}
#| file: R/table_level2_cef_aucu.R
#| out.width: "100%"
```
::::

:::: {#concl-cef-aucu}

`r cef_txt_1_5[1,1]`

::::
:::

::: {#container-cef-er-cex style="clear: both"}

<!-- empty line to ensure next heading leaves enough space -->
<div style="height: 1px"></div>

:::: {#chart-cef-er-cex class="mychart"}
```{r chart-cef-cex, R.options = (cz=c("@@cz_index@@", "@@cz_type@@"))}
#| file: R/chart_level2_cef_cex.R
#| out.width: "100%"
```

```{r table-cef-cex, R.options = (cz=c("@@cz_index@@", "@@cz_type@@"))}
#| file: R/table_level2_cef_cex.R
#| out.width: "100%"
```
::::

:::: {#concl-cef-er-cex}


::::
:::

::: {#container-cef-er-reg-res style="clear: both"}

<!-- empty line to ensure next heading leaves enough space -->
<div style="height: 1px"></div>

:::: {#chart-cef-reg-res class="mychart"}
```{r chart-cef-reg-res, options = (cz=c("@@cz_index@@", "@@cz_type@@"))}
#| file: R/chart_level2_cef_reg_res.R
#| out.width: "100%"
```

```{r chart-cef-er-reg-res_aucu, options = (cz=c("1", "enroute"))}
#| file: R/chart_level2_cef_er_reg_res_aucu.R
#| out.width: "100%"
```

::::

:::: {#concl-cef-reg-res}

`r cef_txt_1_10[1,1]`

::::
:::

::: {#container-cef-reg-res-main-ansp style="clear: both"}

<!-- empty line to ensure next heading leaves enough space -->
<div style="height: 1px"></div>

:::: {#chart-cef-reg-res-ansp class="mychart"}
```{r chart-cef-reg-res-ansp, options = (cz=c("@@cz_index@@", "@@cz_type@@"))}
#| file: R/chart_level2_cef_reg_res_ansp.R
#| out.width: "100%"
```
::::

:::: {#chart-cef-reg-res-main-ansp class="mychart"}
```{r chart-cef-er-reg-res-main-ansp, options = (cz=c("@@cz_index@@", "@@cz_type@@"))}
#| file: R/chart_level2_cef_reg_res_main_ansp.R
#| out.width: "100%"
```

::::

:::: {#concl-cef-er-reg-res-main-ansp}

**`r cef_txt_1_13[1,1]`**

`r cef_txt_1_13[2,1]`

**`r cef_txt_1_13[3,1]`**

`r cef_txt_1_13[4,1]`


::::
:::
