project:
  type: website
  execute-dir: project
  
website:
  title: "PRB Annual Monitoring Report"
  search: false 
  favicon: "images/prb_logo_smaller.png"
  page-navigation: true
  navbar:
    title: false
    background: "#f8f9fa"
    logo: "images/prb_logo.png"
    left: 
      - href: https://www.sesperformance.eu/
        text: Home
      - href: https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/ses-rp3/
        text: SES view
      - text: "State view"
        menu:
          - text: "Austria"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/austria/'
          - text: "Belgium"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/belgium/'
          - text: "Bulgaria"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/bulgaria/'
          - text: "Croatia"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/croatia/'
          - text: "Cyprus"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/cyprus/'
          - text: "Czech Republic"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/czech-republic/'
          - text: "Denmark"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/denmark/'
          - text: "Estonia"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/estonia/'
          - text: "Finland"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/finland/'
          - text: "France"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/france/'
          - text: "Germany"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/germany/'
          - text: "Greece"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/greece/'
          - text: "Hungary"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/hungary/'
          - text: "Ireland"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/ireland/'
          - text: "Italy"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/italy/'
          - text: "Latvia"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/latvia/'
          - text: "Lithuania"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/lithuania/'
          - text: "Luxembourg"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/luxembourg/'
          - text: "Malta"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/malta/'
          - text: "Netherlands"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/netherlands/'
          - text: "Norway"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/norway/'
          - text: "Poland"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/poland/'
          - text: "Portugal"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/portugal/'
          - text: "Romania"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/romania/'
          - text: "Slovakia"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/slovakia/'
          - text: "Slovenia"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/slovenia/'
          - text: "Spain"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/spain/'
          - text: "Sweden"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/sweden/'
          - text: "Switzerland"
            href: 'https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/switzerland/'
            # ---
      - href: https://www.eurocontrol.int/performance/oscar/prb-monitoring-test/2022/network-manager/
        text: NM View
      - href: https://www.sesperformance.eu/about
        text: About
      - href: https://transport.ec.europa.eu/transport-modes/air/single-european-sky/ses-performance-and-charging/publications_en
        text: Publications {{< fa external-link-alt >}}
        target: "_blank"

  sidebar: 
    contents:
      - text: '<b style= "font-size: 1.2rem">{{< var doc.country >}}</b>'
        href: index.html
      - section: "<b>Overview</b>"
        contents:
# block level1 ses beginning
          - text: "Contextual information"
            href: index.html#contextual-information
          - text: "Main PRB findings"
            href: index.html#main-prb-findings--
          - text: "Traffic"
            href: index.html#traffic-ses-rp3-area
          - text: "Safety"
            href: index.html#safety-ses-rp3-area
          - text: "Environment"
            href: index.html#environment-ses-rp3-area
          - text: "Capacity"
            href: index.html#capacity-ses-rp3-area
          - text: "Cost-efficiency"
            href: index.html#cost-efficiency-ses-rp3-area
      - text: "---"
# block level1 ses end
# 
  # site-url: "https://eurocontrol.int/"

  # page-footer: 
  #   center: 
  #     - href: '/'
  #       text: '© European Union, 2023'
  #     - href: disclaimer.qmd
  #       text: "{{< fa triangle-exclamation >}} Disclaimer"
  #     - href: mailto:prb-office@prb.eusinglesky.eu
  #       text: '{{< fa envelope color="#ffffff">}} prb-office@prb.eusinglesky.eu'
      # - text: 'Powered by EUROCONTROL'
      #   href: 'https://www.eurocontrol.int/' 

format:
  html:
    theme: cosmo
    toc: false
    toc-depth: 3
    number-sections: false
    number-depth: 2
    page-layout: full
    css: styles.css
    link-external-newwindow: true
    link-external-icon: true
    # link-external-filter: '^(?:http:|https:)\/\/ansperformance\.eu\/|^(?:http:|https:)\/\/.*ace-handbook\.netlify\.app\/'
    grid:
      sidebar-width: 200px
      margin-width: 200px
    
execute:
  echo: false
  warning: false
  
