project:
  type: website

website:
  title: "State view"
  search: false 
  favicon: "images/prb_logo_smaller.png"
  navbar:
    title: false
    background: "#f8f9fa"
    logo: "images/prb_logo.png"
    left: 
      - href: https://ses-eu.github.io/prb-monitoring/
        text: Home
      - href: https://ses-eu.github.io/prb-monitoring/dashboard.html
        text: Interactive dashboard
      - text: "State view"
        menu:
          - text: "Switzerland"
            href: index.qmd
            # ---
          - text: "Cyprus"
            href: index.qmd
      - href: https://ses-eu.github.io/prb-monitoring/about.html
        text: About
      - href: https://transport.ec.europa.eu/transport-modes/air/single-european-sky/ses-performance-and-charging/publications_en
        text: Publications {{< fa external-link-alt >}}
        target: "_blank"

  sidebar:
    contents:
      - safety.qmd
      - section: "2 Environment"
        contents:
          - environment_kea.qmd
          - environment_apt.qmd
          - environment_mil.qmd
      - section: "3 Capacity"
        contents:
          - capacity_er.qmd
          - capacity_trm.qmd
      - section: "4 Cost-efficiency"
        contents:
          - cost-efficiency.qmd
          - cost-efficiency2.qmd
          - cost-efficiency3.qmd
          - cost-efficiency4-tz.qmd
          - cost-efficiency5-tz.qmd
          - cost-efficiency6-tz.qmd
          - cost-efficiency7-g2g.qmd
  # 
  # site-url: "https://eurocontrol.int/"

  # page-footer: 
  #   center: 
  #     - href: '/'
  #       text: '© European Union, 2023'
  #     - href: disclaimer.qmd
  #       text: "{{< fa triangle-exclamation >}} Disclaimer"
  #     - href: mailto:prb-office@prb.eusinglesky.eu
  #       text: '{{< fa envelope color="#ffffff">}} prb-office@prb.eusinglesky.eu'
      # - text: 'Powered by EUROCONTROL'
      #   href: 'https://www.eurocontrol.int/' 

format:
  html:
    theme: cosmo
    toc: false
    page-layout: full
    css: styles.css
    link-external-newwindow: true
    link-external-icon: true
    # link-external-filter: '^(?:http:|https:)\/\/ansperformance\.eu\/|^(?:http:|https:)\/\/.*ace-handbook\.netlify\.app\/'
    
execute:
  echo: false
  warning: false