[Annual Montiroring Report {{< var doc.year_report >}} - {{< var doc.country >}}]{class="fakeh1"}

## Traffic (En route traffic zone)
::: {.columns}
  
:::: {.column width="60%"}
```{r}
#| file: R/chart_level1_traffic_mvt.R
#| out.height: "300px"
#| out.width: "100%"
```
::::

:::: {.column width="40%"}
Some explanation
::::
:::

::: {.columns}
  
:::: {.column width="60%"}
```{r}
#| file: R/chart_level1_traffic_su.R
#| out.height: "300px"
#| out.width: "100%"
```
::::

:::: {.column width="40%"}
Some explanation
::::
:::

## Safety (Main ANSP)
::: {.columns}
  
:::: {.column width="60%"}
```{r}
#| file: R/chart_level1_saf.R
#| out.height: "300px"
#| out.width: "100%"
```
::::

:::: {.column width="40%"}
Some explanation
::::
:::

## Environment (Member State)
::: {.columns}
  
:::: {.column width="60%"}
```{r}
#| file: R/chart_level1_kea.R
#| out.height: "220px"
#| out.width: "100%"
```
::::

:::: {.column width="40%"}
Some explanation
::::
:::

## Capacity (Member State)
::: {.columns}
  
:::: {.column width="60%"}
```{r}
#| file: R/chart_level1_cap_er.R
#| out.height: "300px"
#| out.width: "100%"
```
::::

:::: {.column width="40%"}
Some explanation
::::
:::

::: {.columns}
  
:::: {.column width="60%"}
```{r}
#| file: R/chart_level1_cap_trm.R
#| out.height: "300px"
#| out.width: "100%"
```
::::

:::: {.column width="40%"}
Some explanation
::::
:::

## Cost-efficiency (En route/Terminal charging zone(s))
::: {.columns}
  
:::: {.column width="60%"}
```{r}
#| file: R/chart_level1_cef_er.R
#| out.height: "300px"
#| out.width: "100%"
```
::::

:::: {.column width="40%"}
Some explanation
::::
:::

::: {.columns}
  
:::: {.column width="60%"}
```{r}
#| file: R/chart_level1_cef_trm.R
#| out.height: "300px"
#| out.width: "100%"
```
::::

:::: {.column width="40%"}
Some explanation
::::
:::