# 1 Safety
### Effectiveness of Safety Management

```{r}
#| file: R/table_saf_eosm.R
#| out.width: "100%"
```

Note: EoSM questionnaire has been updated in RP3 using CANSO Standard of Excellence as the basis, maturity levels of study areas and calculation of the score have been updated too. A direct comparison with  maturity levels and scoring of EoSM used RP2 is not advisable.


### Observations															
Four out of five EoSM components of the ANSP meet the RP3 target level. No improvements were observed over 2022, but only "Safety Risk Management" component is below RP3 target level with three questions to improve during RP3 to achieve RP3 target.

IMPORTANT: EASA/European Commission did not receive the verified questionnaire from the NSA on time. This is an important step to receive confirmation that the self-evaluated questionnaire by the ANSP has been actually verified. It should be sent in due time to allow proper and timely drafting of the Monitoring Report.