[Annual Montiroring Report {{< var doc.year_report >}} - {{< var doc.country >}}]{class="fakeh1"}

## Contextual information
TBadded

## Traffic (En route traffic zone)
::: {.columns}
  
:::: {.column width="60%"}
```{r}
#| file: R/chart_level1_traffic_mvt.R
#| out.width: "100%"
```

::::

:::: {.column width="40%"}
```{r}
mvt_conc <- read_mytable("PRB_findings.xlsx", "traffic_IFR", "Table_Findings_traffic_IFR") %>% 
  filter(Year_Report == year_report, State == country) %>% 
  select(Conclusion) %>% toString() %>% paste0(., "@")

mvt_conc1 <- mvt_conc %>% str_replace_all(c('", ' = '\n\n', '\"' = '', '\n\n\n' = '\n\n')) %>% str_replace(fixed('c('), '') %>%  str_replace(fixed(')@'), '') 
```

`r mvt_conc1`
::::

<br>

:::: {.column width="60%"}
```{r}
#| file: R/chart_level1_traffic_mvt.R
#| out.width: "100%"
```

::::

:::: {.column width="40%"}
```{r}
tsu_conc <- read_mytable("PRB_findings.xlsx", "traffic_SUs", "Table_Findings_traffic_TSU") %>% 
  filter(Year_Report == year_report, State == country) %>% 
  select(Conclusion) %>% toString() %>% paste0(., "@")

tsu_conc1 <- tsu_conc %>% str_replace_all(c('", ' = '\n\n', '\"' = '', '\n\n\n' = '\n\n')) %>% str_replace(fixed('c('), '') %>%  str_replace(fixed(')@'), '') 
```

`r tsu_conc1`
::::
:::

## Safety (Main ANSP)
::: {.columns}
  
:::: {.column width="60%"}
```{r}
#| file: R/chart_level1_saf.R
#| out.width: "100%"
```
::::

:::: {.column width="40%"}
```{r}
saf_conc <- read_mytable("PRB_findings.xlsx", "traffic_SUs", "Table_Findings_traffic_TSU") %>% 
  filter(Year_Report == year_report, State == country) %>% 
  select(Conclusion) %>% toString() %>% paste0(., "@")

saf_conc1 <- saf_conc %>% str_replace_all(c('", ' = '\n\n', '\"' = '', '\n\n\n' = '\n\n')) %>% str_replace(fixed('c('), '') %>%  str_replace(fixed(')@'), '\n') 
```

`r saf_conc1`
::::
:::

## Environment (Member State)
::: {.columns}
  
:::: {.column width="60%"}
```{r}
#| file: R/chart_level1_kea.R
#| out.width: "100%"
```
::::

:::: {.column width="40%"}
```{r}
env_conc <- read_mytable("PRB_findings.xlsx", "environment", "Table_Findings_environment") %>% 
  filter(Year_Report == year_report, State == country) %>% 
  select(Conclusion) %>% toString() %>% paste0(., "@")

env_conc1 <- env_conc %>% str_replace_all(c('", ' = '\n\n', '\"' = '', '\n\n\n' = '\n\n')) %>% str_replace(fixed('c('), '') %>%  str_replace(fixed(')@'), '\n') 
```

`r env_conc1`
::::
:::

## Capacity (Member State)
::: {.columns}
  
:::: {.column width="60%"}
```{r}
#| file: R/chart_level1_cap_er.R
#| out.width: "100%"
```

<br>

```{r}
#| file: R/chart_level1_cap_trm.R
#| out.width: "100%"
```
::::

:::: {.column width="40%"}
```{r}
cap_er_conc <- read_mytable("PRB_findings.xlsx", "ER_capacity", "Table_Findings_ER_capacity") %>% 
  filter(Year_Report == year_report, State == country) %>% 
  select(Conclusion) %>% toString() %>% paste0(., "@")

cap_er_conc1 <- cap_er_conc %>% str_replace_all(c('", ' = '\n\n', '\"' = '', '\n\n\n' = '\n\n')) %>% str_replace(fixed('c('), '') %>%  str_replace(fixed(')@'), '\n') 
```

`r cap_er_conc1`
::::
:::

## Cost-efficiency (En route/Terminal charging zone(s))
::: {.columns}
  
:::: {.column width="60%"}
```{r}
#| file: R/chart_level1_cef_er.R
#| out.width: "100%"
```
<br>
```{r}
#| file: R/chart_level1_cef_trm.R
#| out.width: "100%"
```
::::

:::: {.column width="40%"}
```{r}
cef_conc <- read_mytable("PRB_findings.xlsx", "cost-efficiency", "Table_Findings_CEFF") %>% 
  filter(Year_Report == year_report, State == country) %>% 
  select(Conclusion) %>% toString() %>% paste0(., "@")

cef_conc1 <- cef_conc %>% str_replace_all(c('", ' = '\n\n', '\"' = '', '\n\n\n' = '\n\n')) %>% str_replace(fixed('c('), '') %>%  str_replace(fixed(')@'), '\n') 
```

`r cap_er_conc1`
::::
:::

