## Document download

### PRB Annual Monitoring Report 2023

::: {.grid}
:::: {.g-col-1}
::::

:::: {.g-col-10}

|  |  |  |
|-----------------------|-----------------------|------------------------|
| [SES RP3](download/2023/PRB-Annual-Monitoring-Report_SES%20RP3_2023.pdf) | [France](download/2023/PRB-Annual-Monitoring-Report_France_2023.pdf) | [Netherlands](download/2023/PRB-Annual-Monitoring-Report_Netherlands_2023.pdf) |
|  | [Germany](download/2023/PRB-Annual-Monitoring-Report_Germany_2023.pdf) | [Network Manager](download/2023/PRB-Annual-Monitoring-Report_Network%20Manager_2023.pdf) |
| [Austria](download/2023/PRB-Annual-Monitoring-Report_Austria_2023.pdf) | [Greece](download/2023/PRB-Annual-Monitoring-Report_Greece_2023.pdf) | [Norway](download/2023/PRB-Annual-Monitoring-Report_Norway_2023.pdf) |
| [Belgium](download/2023/PRB-Annual-Monitoring-Report_Belgium_2023.pdf) | [Hungary](download/2023/PRB-Annual-Monitoring-Report_Hungary_2023.pdf) | [Poland](download/2023/PRB-Annual-Monitoring-Report_Poland_2023.pdf) |
| [Bulgaria](download/2023/PRB-Annual-Monitoring-Report_Bulgaria_2023.pdf) | [Ireland](download/2023/PRB-Annual-Monitoring-Report_Ireland_2023.pdf) | [Portugal](download/2023/PRB-Annual-Monitoring-Report_Portugal_2023.pdf) |
| [Croatia](download/2023/PRB-Annual-Monitoring-Report_Croatia_2023.pdf) | [Italy](download/2023/PRB-Annual-Monitoring-Report_Italy_2023.pdf) | [Romania](download/2023/PRB-Annual-Monitoring-Report_Romania_2023.pdf) |
| [Cyprus](download/2023/PRB-Annual-Monitoring-Report_Cyprus_2023.pdf) | [Latvia](download/2023/PRB-Annual-Monitoring-Report_Latvia_2023.pdf) | [Slovakia](download/2023/PRB-Annual-Monitoring-Report_Slovakia_2023.pdf) |
| [Czeck Republic](download/PRB-Annual-Monitoring-Report_Czeck%20Republic_2023.pdf) | [Lithuania](download/2023/PRB-Annual-Monitoring-Report_Lithuania_2023.pdf) | [Slovenia](download/2023/PRB-Annual-Monitoring-Report_Slovenia_2023.pdf) |
| [Denmark](download/2023/PRB-Annual-Monitoring-Report_Denmark_2023.pdf) | [Luxembourg](download/2023/PRB-Annual-Monitoring-Report_Luxembourg_2023.pdf) | [Spain](download/2023/PRB-Annual-Monitoring-Report_Spain_2023.pdf) |
| [Estonia](download/2023/PRB-Annual-Monitoring-Report_Estonia_2023.pdf) | [Malta](download/2023/PRB-Annual-Monitoring-Report_Denmark_2023.pdf) | [Sweden](download/2023/PRB-Annual-Monitoring-Report_Sweden_2023.pdf) |
| [Finland](download/2023/PRB-Annual-Monitoring-Report_Finland_2023.pdf) | [MUAC](download/2023/PRB-Annual-Monitoring-Report_MUAC_2023.pdf) | [Switzerland](download/2023/PRB-Annual-Monitoring-Report_Switzerland_2023.pdf) |

:::: 

:::: {.g-col-1}
::::
:::