```{r, eval=TRUE}
if (exists("data_folder") == FALSE) {
  source("R/parameters.R")
}
```

[Annual Monitoring Report {{< var doc.year_report >}} - SES View]{.fakeh1}

## Contextual information


## Main PRB findings - {{< var doc.year_report >}}

```{r}
tsu_conc <- read_mytable("PRB_findings.xlsx", "main", "Table_Findings_main") %>% 
  filter(Year_Report == year_report, State == 'SES') %>% 
  select(Conclusion) %>% toString() %>% paste0(., "@")

main_conc1 <- tsu_conc %>% str_replace_all(c('", ' = '\n\n', '\"' = '', '\n\n\n' = '\n\n')) %>% str_replace(fixed('c('), '') %>%  str_replace(fixed(')@'), '') 
```

`r main_conc1`

## Traffic (SES RP3 area)

::: {#container-mvt}
:::: {#chart-mvt style="float: left; width: 60%"}
```{r}
#| file: R/chart_level1_traffic_mvt.R
#| out.width: "100%"
```
::::

:::: {#concl-mvt}
```{r}
mvt_conc <- read_mytable("PRB_findings.xlsx", "traffic_IFR", "Table_Findings_traffic_IFR") %>% 
  filter(Year_Report == year_report, State == 'SES') %>% 
  select(Conclusion) %>% toString() %>% paste0(., "@")

mvt_conc1 <- mvt_conc %>% str_replace_all(c('", ' = '\n\n', '\"' = '', '\n\n\n' = '\n\n')) %>% str_replace(fixed('c('), '') %>%  str_replace(fixed(')@'), '') 
```

`r mvt_conc1`
::::
:::

::: {#container-su style="clear: both"}

<br>

:::: {#chart-su style="float: left; width: 60%"}
```{r}
#| file: R/chart_level1_traffic_su.R
#| out.width: "100%"
```
::::

:::: {#concl-su}
```{r}
tsu_conc <- read_mytable("PRB_findings.xlsx", "traffic_SUs", "Table_Findings_traffic_TSU") %>% 
  filter(Year_Report == year_report, State == 'SES') %>% 
  select(Conclusion) %>% toString() %>% paste0(., "@")

tsu_conc1 <- tsu_conc %>% str_replace_all(c('", ' = '\n\n', '\"' = '', '\n\n\n' = '\n\n')) %>% str_replace(fixed('c('), '') %>%  str_replace(fixed(')@'), '') 
```

`r tsu_conc1`
::::
:::

::: {#container-saf style="clear: both"}

<!-- empty line to ensure next heading leaves enough space -->
<div style="height: 1px"></div>

## Safety (SES RP3 area)

:::

::: {#container-env style="clear: both"}

<!-- empty line to ensure next heading leaves enough space -->
<div style="height: 1px"></div>

## Environment (SES RP3 area)

:::: {#chart-env style="float: left; width: 60%"}
```{r}
#| file: R/chart_level1_kea.R
#| out.width: "100%"
```
::::

:::: {#concl-env}
```{r}
env_conc <- read_mytable("PRB_findings.xlsx", "environment", "Table_Findings_environment") %>% 
  filter(Year_Report == year_report, State == 'SES') %>% 
  select(Conclusion) %>% toString() %>% paste0(., "@")

env_conc1 <- env_conc %>% str_replace_all(c('", ' = '\n\n', '\"' = '', '\n\n\n' = '\n\n')) %>% str_replace(fixed('c('), '') %>%  str_replace(fixed(')@'), '\n') 
```

`r env_conc1`
::::
:::

::: {#container-cap style="clear: both"}

## Capacity (SES RP3 area)
<!-- empty line to ensure next heading leaves enough space -->
<div style="height: 1px"></div>

:::: {#chart-cap style="float: left; width: 60%"}
```{r}
#| file: R/chart_level1_cap_er.R
#| out.width: "100%"
```
::::

:::: {#concl-cap}
```{r}
cap_er_conc <- read_mytable("PRB_findings.xlsx", "ER_capacity", "Table_Findings_ER_capacity") %>% 
  filter(Year_Report == year_report, State == 'SES') %>% 
  select(Conclusion) %>% toString() %>% paste0(., "@")

cap_er_conc1 <- cap_er_conc %>% str_replace_all(c('", ' = '\n\n', '\"' = '', '\n\n\n' = '\n\n')) %>% str_replace(fixed('c('), '') %>%  str_replace(fixed(')@'), '\n') 
```

`r cap_er_conc1`
::::
:::


::: {#container-cef style="clear: both"}
<!-- empty line to ensure next heading leaves enough space -->
<div style="height: 1px"></div>

## Cost-efficiency (SES RP3 area)

:::: {#chart-cef style="float: left; width: 60%"}
```{r}
#| file: R/chart_level1_cef_er_ses.R
#| out.width: "100%"
```
::::

:::: {#concl-cef}
```{r}
cef_conc <- read_mytable("PRB_findings.xlsx", "cost-efficiency", "Table_Findings_CEFF") %>% 
  filter(Year_Report == year_report, State == 'SES') %>% 
  select(Conclusion) %>% toString() %>% paste0(., "@")

cef_conc1 <- cef_conc %>% str_replace_all(c('", ' = '\n\n', '\"' = '', '\n\n\n' = '\n\n')) %>% str_replace(fixed('c('), '') %>%  str_replace(fixed(')@'), '\n') 
```

`r cef_conc1`
::::
:::

