```{r, eval=TRUE}
if (knitr::is_latex_output()) {
  mywidth <- params$mywidth_pdf
  myheight <- params$myheight_pdf
  myfont <- params$myfont_pdf
  mylinewidth <- params$mylinewidth_pdf
  mymargin <- params$mymargin_pdf
}
```

# SES View

## Main PRB findings - {{< var doc.year_report >}}

```{r main-concl}
main_conc1 <- get_prb_conclusions("PRB_findings.xlsx", "main", "Table_Findings_main")
```

`r main_conc1`

## Traffic (SES RP3 area)
<!-- https://tex.stackexchange.com/questions/215442/is-there-a-way-to-set-a-parbox-to-a-minimum-height -->

```{=tex}
\setlength{\fboxrule}{0pt} % Set the border width to 0pt (no border)
\setlength{\fboxsep}{0pt} % Remove padding
\sbox{0}{\parbox{1\textwidth}{

\begin{wrapfigure}[14]{l}{0.58\linewidth}
\vspace{-15pt}
```

```{r}
#| file: R/chart_level1_traffic_mvt.R
#| out.width: "100%"
```

```{=tex}
\end{wrapfigure}
\setlength\parskip{1em plus 0.8em} % Space between paragraphs
```


```{r}
mvt_conc1 <- get_prb_conclusions("PRB_findings.xlsx", "traffic_IFR", "Table_Findings_traffic_IFR")
```

`r mvt_conc1`

```{=tex}
}}
\ifdim\dimexpr\ht0+\dp0<7.0cm 
\dp0\dimexpr7.0cm-\ht0\fi

\fbox{\usebox{0}}

\sbox{0}{\parbox{1\textwidth}{

\begin{wrapfigure}[14]{l}{0.58\linewidth}
\vspace{-15pt}
```

```{r}
#| file: R/chart_level1_traffic_su.R
#| out.width: "100%"
```

```{=tex}
\end{wrapfigure}
\setlength\parskip{1em plus 0.8em} % Space between paragraphs
```

```{r}
tsu_conc1 <- get_prb_conclusions("PRB_findings.xlsx", "traffic_SUs", "Table_Findings_traffic_TSU")
```

`r tsu_conc1`

```{=tex}
}}
\ifdim\dimexpr\ht0+\dp0<7.0cm 
\dp0\dimexpr7.0cm-\ht0\fi

\fbox{\usebox{0}}
```

```{=tex}
{
```

## Safety (SES RP3 area)

```{=tex}
\sbox{0}{\parbox{1\textwidth}{

\begin{wrapfigure}[14]{l}{0.58\linewidth}
\vspace{-15pt}
```

```{r}
#| file: R/chart_level1_saf_ses.R
#| out.width: "100%"
```

```{=tex}
\end{wrapfigure}
\setlength\parskip{1em plus 0.8em} % Space between paragraphs
```

```{r}
saf_conc1 <- get_prb_conclusions("PRB_findings.xlsx", "safety", "Table_Findings_safety")
```

`r saf_conc1`
```{=tex}
}}
\ifdim\dimexpr\ht0+\dp0<7.0cm 
\dp0\dimexpr7.0cm-\ht0\fi

\fbox{\usebox{0}}
```

## Environment (SES RP3 area)

```{=tex}
\sbox{0}{\parbox{1\textwidth}{

\begin{wrapfigure}[14]{l}{0.58\linewidth}
\vspace{-15pt}

```

```{r chart-env-kea, options = (doclevel=c("level1"))}
#| file: R/chart_level1_kea.R
#| out.width: "100%"
```

```{=tex}
\end{wrapfigure}

\setlength\parskip{1em plus 0.8em} % Space between paragraphs
```

```{r}
env_conc1 <- get_prb_conclusions("PRB_findings.xlsx", "environment", "Table_Findings_environment")
```

`r env_conc1`
```{=tex}
}}
\ifdim\dimexpr\ht0+\dp0<7.0cm 
\dp0\dimexpr7.0cm-\ht0\fi

\fbox{\usebox{0}}
```

## Capacity (SES RP3 area)

```{=tex}
\sbox{0}{\parbox{1\textwidth}{

\begin{wrapfigure}[14]{l}{0.58\linewidth}
\vspace{-15pt}

```

```{r chart-cap-er, options = (cztype=c("enroute"))}
#| file: R/chart_level1_cap.R
#| out.width: "100%"
```

```{r chart-cap-trm, options = (cztype=c("terminal"))}
#| file: R/chart_level1_cap.R
#| out.width: "100%"
```

```{=tex}
\end{wrapfigure}

\setlength\parskip{1em plus 0.8em} % Space between paragraphs
```

```{r}
cap_er_conc1 <- get_prb_conclusions("PRB_findings.xlsx", "ER_capacity", "Table_Findings_ER_capacity")
```

`r cap_er_conc1`
```{=tex}
}}
\ifdim\dimexpr\ht0+\dp0<7.0cm 
\dp0\dimexpr7.0cm-\ht0\fi

\fbox{\usebox{0}}
```

## Cost-efficiency (SES RP3 area)

```{=tex}
\sbox{0}{\parbox{1\textwidth}{

\begin{wrapfigure}[14]{l}{0.58\linewidth}
\vspace{-15pt}

```

```{r}
#| file: R/chart_level1_cef_er_ses.R
#| out.width: "100%"
```

```{r chart-cef-trm-1, options = (cz=c("1", "terminal", "level1"))}
#| file: R/chart_level1_cef.R
#| out.width: "100%"
```

```{=tex}
\end{wrapfigure}

\setlength\parskip{1em plus 0.8em} % Space between paragraphs
```

```{r}
cef_conc1 <- get_prb_conclusions("PRB_findings.xlsx", "cost-efficiency", "Table_Findings_CEFF")
```

`r cef_conc1`
```{=tex}
}}
\ifdim\dimexpr\ht0+\dp0<7.0cm 
\dp0\dimexpr7.0cm-\ht0\fi

\fbox{\usebox{0}}
```